import { Host_Grotesk, Sofia_Sans_Condensed } from "next/font/google";
import "./globals.css";

const Sofia_Sans_Cond = Sofia_Sans_Condensed({
  variable: "--font-sofia-condensed-sans",
  weight:"700"
});

const Host_Grot = Host_Grotesk({
  variable: "--font-host-grotesk",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${Sofia_Sans_Cond.variable} ${Host_Grot.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
